# Spotify tools require access to the internal tap and its Git remote.
tap "spotify/public"
tap "spotify/sptaps", "git@ghe.spotify.net:shared/homebrew-spotify.git"

# Public tools used for local development. Homebrew installs their libraries as dependencies.
brew "argo"
brew "argocd"
brew "awscli"
brew "cmake"
brew "devspace"
brew "gcc"
brew "gh"
brew "go"
brew "gradle"
brew "graphviz"
brew "helm"
brew "htop"
brew "istioctl"
brew "jq"
brew "jsonnet"
brew "kube-score"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "lazygit"
brew "macvim"
brew "maven"
brew "mtr"
brew "nmap"
brew "node"
brew "pandoc"
brew "protobuf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "sbt"
brew "scala"
brew "skaffold"
brew "tfenv"
brew "tmux"
brew "tree"
brew "velero"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "zsh-completions"

brew "spotify/public/gcs-avro-tools"
brew "spotify/public/helios"
brew "spotify/public/helios-solo"
brew "spotify/sptaps/data-endpoints-cli"
brew "spotify/sptaps/hades-cli"
brew "spotify/sptaps/hmtools"
brew "spotify/sptaps/kubectl-site"
brew "spotify/sptaps/styx-cli"

# Desktop apps and runtimes.
cask "corretto@11"
cask "gcloud-cli"
cask "gitify"
cask "intellij-idea"
cask "iterm2"
cask "miniforge"
cask "spotify"
cask "visual-studio-code"
