# Public tools used for local development. Homebrew installs their libraries as dependencies.
# Install Spotify-only tools separately from Brewfile.spotify after connecting to the private network.
brew "argo"
brew "argocd"
brew "awscli"
brew "cmake"
brew "devspace"
brew "gcc"
brew "gh"
brew "go"
brew "gradle"
brew "graphviz"
brew "helm"
brew "htop"
brew "istioctl"
brew "jq"
brew "jsonnet"
brew "kube-score"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "lazygit"
brew "macvim"
brew "maven"
brew "mtr"
brew "nmap"
brew "node"
brew "pandoc"
brew "protobuf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "sbt"
brew "scala"
brew "skaffold"
brew "tfenv"
brew "tmux"
brew "tree"
brew "velero"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "zsh-completions"

# Desktop apps and runtimes.
cask "corretto@11"
cask "gcloud-cli"
cask "gitify"
cask "intellij-idea"
cask "iterm2"
cask "miniforge"
cask "spotify"
cask "visual-studio-code"

